version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)

  build:
    commands:
      - export IMAGE="$REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - docker build -t $IMAGE .
      - docker push $IMAGE
      
      # Build config
      - deploy/create-config-files.sh $IMAGE
artifacts:
  discard-paths: yes
  files:
    - "deploy/hello-world.template.yml"
    - "hello-world.*.config.json"