Mappings:
  Accounts:
    Dev:
      VpcId: vpc-086a061899dc4ff81
      Domain: dev.brigh.id

    Prod:
      VpcId: vpc-01c1c70487a3ff7b0
      Domain: brigh.id

Resources:
  DevListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue cfn-core:HttpsListenerArn
      Priority: 1
      Actions:
        - Type: forward
          TargetGroupArn: !Ref DevTargetGroup
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !FindInMap [Accounts, Dev, Domain]
              - !FindInMap [Accounts, Prod, Domain]
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - /hello-world
              
  DevTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: cfn-hello-world-dev
      TargetType: ip
      VpcId: !FindInMap [Accounts, Dev, VpcId]
      Port: 443
      Protocol: HTTP